### ISSUE TITLE
User role visualization tool

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Roles-Management#1]

**Comment by brashrebel** [comment]
I'm envisioning a submenu under Users. This page will ideally list each user role so that maybe one could click on each role to view the role's capabilities.

**Comment by joelworsham** [comment]
You read my mind

**Comment by joelworsham** [comment]
Viewable from Users -> View Roles: this page http://jacksoncollege.staging.wpengine.com/wp-admin/users.php?page=jc-role-visualizer
